robbie:  
  hip_balance_controller:
    type: objective_controller/ObjectiveController
    joint: hip_joint
    pid:
     p: 2000
     i: 0.1
     d: 30
     i_clamp: 0.3
     publish_state: True
    setpoint_topic: /setpoint
    objective_topic: /robbie/ssm/delta

  # height_controller:
  #   type: objective_controller/ObjectiveController
  #   joint: hip_joint
  #   pid:
  #    p: 2000
  #    i: 0.1
  #    d: 30
  #    i_clamp: 0.3
  #    publish_state: True
  #   setpoint_topic: /robbie/height/command
  #   objective_topic: /robbie/height/delta
  # height_controller:
  #   type: objective_controller/ESObjectiveController
  #   joint: hip_joint
  #   pid:
  #    p: 2500
  #    i: 0.1
  #    d: 30
  #    i_clamp: 0.3
  #    publish_state: True
  #   setpoint_topic: /robbie/height/command
  #   objective_topic: /robbie/height/delta
  #   alpha: 0.8
  height_controller:
    type: objective_controller/ESObjectiveController
    joint: knee_joint
    pid:
     p: 3000
     i: 0.1
     d: 30
     i_clamp: 0.3
     publish_state: True
    setpoint_topic: /setpoint
    objective_topic: /robbie/ssm/delta
    alpha: 0.75

  special_height_controller:
    type: objective_controller/WeightedObjectiveController
    joint: knee_joint
    pid:
     p: 3000
     i: 0.1
     d: 30
     i_clamp: 0.3
     publish_state: True
    setpoint_topic: /robbie/height/command
    objective_one: /robbie/height/delta
    objective_two: /robbie/ssm_delta
    K1: 1
    K2: 0
    alpha: 0.75

  special_hip_balance_controller:
    type: objective_controller/WeightedObjectiveController
    joint: hip_joint
    pid:
     p: 3000
     i: 0.1
     d: 30
     i_clamp: 0.3
     publish_state: True
    setpoint_topic: /robbie/height/command
    objective_one: /robbie/height/delta
    objective_two: /robbie/ssm_delta
    K1: 1
    K2: 0
    alpha: 0.75



    # alpha: 0.78
