robbie:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  # Joint Controllers ---------------------------------------
  leftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: l_wheel
    pid: {p: 100.0, i: 0.1, d: 10.0}
  rightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: r_wheel
    pid: {p: 100.0, i: 0.1, d: 10.0}
  shankWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: shank_wheel
    pid: {p: 100.0, i: 0.1, d: 10.0}
  shank_position_controller:
    type: effort_controllers/JointPositionController
    joint: calf_shank
    pid: {p: 100.0, i: 0.1, d: 10.0}
  knee_position_controller:
    type: effort_controllers/JointPositionController
    joint: calf_thigh
    pid: {p: 100.0, i: 0.1, d: 10.0}
  hip_position_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
       - thigh_torso
       - calf_thigh
    constraints:
        goal_time: 1
        stopped_velocity_tolerance: 0.05
        thigh_torso: {trajectory: 0.1, goal: 0.1}
        calf_thigh: {trajectory: 0.1, goal: 0.1}
  l_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: torso_shoulder_l
    pid: {p: 100.0, i: 0.1, d: 10.0}
  r_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: torso_shoulder_r
    pid: {p: 100.0, i: 0.1, d: 10.0}
  r_lwr_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_shoulder_r
    pid: {p: 100.0, i: 0.1, d: 10.0}
  l_lwr_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_shoulder_l
    pid: {p: 100.0, i: 0.1, d: 10.0}
  rb_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: b_wheel_r
    pid: {p: 100.0, i: 0.1, d: 10.0}
  lb_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: b_wheel_l
    pid: {p: 100.0, i: 0.1, d: 10.0}
  b_position_controller:
    type: effort_controllers/JointPositionController
    joint: torso_butt
    pid: {p: 100.0, i: 0.1, d: 10.0}


